version: '2.1'

services:
  napalm-logs:
    image: mirceaulinic/napalm-logs:0.5.0
    hostname: napalm-logs
    container_name: napalm-logs
    environment:
      - LOG_LEVEL
    volumes:
      - ./napalm-logs.conf:/etc/napalm/logs
    network_mode: host
    ports:
      - "49017"
  salt-master:
    image: mirceaulinic/salt-master:2017.7.5
    hostname: salt-master
    container_name: salt-master
    environment:
      - LOG_LEVEL
    volumes:
      - ./master:/etc/salt/master
      - ./pillar/:/etc/salt/pillar/
      - ./states/:/etc/salt/states/
      - ./reactor:/etc/salt/reactor/
    network_mode: host
  salt-proxy:
    image: mirceaulinic/salt-proxy:2017.7.5
    hostname: ${PROXYID}
    container_name: salt-proxy-${PROXYID}
    volumes:
      - ./proxy:/etc/salt/proxy
    environment:
      - LOG_LEVEL
      - PROXYID
    network_mode: host
